### PR TITLE
Group frontend

### LINKED ISSUE #44: Implement user groups
User groups collect bills for a group of users and maintain all users' balances.
All group members can add bills to the group.

### LINKED ISSUE #97: Frontend functionality for groups
Get the correct groups for the user and display them. Add the functionality of choosing whether you want to create a group or a bill.

### PR DESCRIPTION
**Pull request by jeysbach**
Added the group functionality in the frontend.
Test suite passes on clean database.
Did not add e2e tests but I think we can get away with that since this feature is a could-have.

### CODE REVIEW

**Comment by jeysbach** [comment]
This branch also already contains the bugfix branch because I needed some of the changes here.

**Review by astamagg — CHANGES_REQUESTED** [review]
The pay pages timeouts when loading on this branch, checked the master and it does not happen there.

**Comment by jeysbach** [comment]
your database probably contains old transactions, can you try it again after resetting your database?

**Review by astamagg — APPROVED** [review]
It works when I removed everything from my database 👍

**Pull request merged**
