### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by jwbambacht**
- Fix change of text on pay button and remove element instead of reload page
- Layout set paid button and participants on bill
- Default Ripple server to altnet in example .env
- Fix issues with input validation on request bill page

### CODE REVIEW

**Comment by astamagg** [comment]
There is a conflict with the master, can you check if before I verify?

**Comment by jwbambacht** [comment]
> There is a conflict with the master, can you check if before I verify?

Still improving more things, I'll let u know when it's done.

**Comment by jwbambacht** [comment]
Furthermore:
- Fix for request bill input validation
- Update balance after payment is finished
- Removed from attribute on bill overview since it is always yourself
- Changed data pre-loading to ejs instead of after page loaded on bill and account page
- Fix incorrect weight translation on request bill

**Comment by jwbambacht** [comment]
Also adds the functionality of deleting a settled bill from the bill overview.

**Review by astamagg — APPROVED** [review]
Looks good, added the process.env.PORT and did a little bit of added styling

**Pull request merged**
