### PR TITLE
Added script for db creation

### LINKED ISSUE #8: Setup PostgreSQL and create seed script
Create a first super basic DB schema and a script that cleans and recreates the DB on startup

### LINKED ISSUE #26: Implement seeding with TypeORM-seeding

### PR DESCRIPTION
**Pull request by tomdevman**
Added new .sh script for db creation (tested this new workflow and it's somewhat faster than the docker-compose one).

### CODE REVIEW

**Comment by roemba** [comment]
Closes #8

**Comment by roemba** [comment]
It looks good but I cannot get this to work under Windows (because of the shell script). I see two options for this: either there needs to be an equivalent Powershell script to interface with docker OR seeding the database becomes optional when running the server...

**Comment by tomdevman** [comment]
> It looks good but I cannot get this to work under Windows (because of the shell script). I see two options for this: either there needs to be an equivalent Powershell script to interface with docker OR seeding the database becomes optional when running the server...

I removed starting the db when running `npm run dev` and now whoever wants to start the docker container running the postgres db can first run `npm run db`. When running `npm run dev`, the seeding script will be called and the two users (appropiately named Alice and Bob 😄) will be added to the db. We can use the secrets from the .env file to login with the two users

**Review by roemba — APPROVED** [review]
Works as expected, nice that it is now optional if you want to start a docker container automatically. I tested it with the latest version of master.

**Pull request merged**
