### PR TITLE
Bill Overview and Request page modifications

### PR DESCRIPTION
**Pull request by jwbambacht**
On submit of a new bill, a success message is shown and the form is cleared. Bill overview page is adjusted to include participants and their weights, icon is shown to see who paid their part.

### CODE REVIEW

**Review by astamagg — COMMENTED** [review]
It might be good to also add a: Creating bill... when the button is pressed because otherwise it looks unresponsive before announcing success. Also I think it might be better placed above the button or below the title to make the status message more noticeable.

**Comment by jwbambacht** [comment]
> It might be good to also add a: Creating bill... when the button is pressed because otherwise it looks unresponsive before announcing success. Also I think it might be better placed above the button or below the title to make the status message more noticeable.

I have processed your comments in the new commit.

**Comment by roemba** [comment]
Closes #79

**Review by roemba — APPROVED** [review]
Works well and looks nice. I'll add the server side validation on a separate branch  as part of #78 , although you already added client side validation for the request page

**Pull request merged**
