### PR TITLE
Email notifications

### LINKED ISSUE #81: Receive a notification via email if a payment request needs to be payed

### LINKED ISSUE #82: Receive a notification via e-mail if someone payed a bill

### PR DESCRIPTION
**Pull request by tomdevman**
**UPDATES**
Implemented email notifications on new payment requests and new payments received. To test this functionality I also created a new yahoo email account, details of how to login will follow on our team's discord chat. Finally, the email field is also marked as required now for new users that register.

**IMPORTANT NOTES**
- this update introduces a new package so you need to run `npm install`
- please also update you `.env` file with the SENDGRID_API_KEY that was shared on our team's **discord** (this is to keep the api key safe)

**ISSUES**
- closes #81 
- closes #82

### CODE REVIEW

**Comment by jeysbach** [comment]
I think it would be better to keep email optional and only send notifications if the user registered their email.

**Comment by astamagg** [comment]
Yes I agree, we can then just say that if you don't provide an email you will not get notifications.

**Comment by roemba** [comment]
I disagree, new users would not know that they can use this feature if it is not enabled by default. Enabling by default requires that there is an email registered. 

They can always turn it off via the email notifications toggle.

**Review by astamagg — APPROVED** [review]
Works as expected

**Pull request merged**
